### PR TITLE
change delems from parse test to more generic ones

### PR DESCRIPTION
**Pull request by odjhey**
issue https://github.com/sbcgua/abap_data_parser/issues/2 : veri* data elements not in s/4 hana 1709. Change to more generic ones

### CODE REVIEW

**Comment by sbcgua** [comment]
OK for the change, but please resolve the conflicts (rebase ?)

**Comment by sbcgua** [comment]
Seems to be because the commit is before my latest updates with serializer. By the way it uses the veri_ types also. Try to rebase your commit onto latest code pls.

**Comment by odjhey** [comment]
sorry bout that, will checkout ur latest and rebase. thanks!

**Comment by odjhey** [comment]
Please review PR. Have a good day!

**Comment by sbcgua** [comment]
yeap, merging, thanks ! :)

**Pull request merged**
